version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  app:
    restart: always
    build: .
    ports:
      - 15111:15111
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["python", "server.py"]
