version: '2.1'

networks: 
  soa-shipping:
    driver: bridge

volumes: 
  db:

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - soa-shipping
    volumes:
          - "db:/var/lib/postgresql/data"
  app:
    restart: always
    build: .
    ports:
      - 15111:15111
    networks:
      - soa-shipping
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["./docker-entrypoint.sh"]